### ISSUE TITLE
Do not program the MCU all the time to save write cycles.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-creator-init#1]
Do not program the MCU all the time to save write cycles.

**Comment by arhuaco** [comment]
Creating a new Debian package for the firmware. This way the firmware only gets programmed when the package changes. I need to learn more about package dependencies to finish this task.

**Comment by brianofrokk3r** [comment]
@arhuaco did we update this already?

**Comment by arhuaco** [comment]
I got another issue yesterday from Andrés. This issue requires a bit programming to check the hashes of the firmware and a bit more of programming. I'll work on it today.

**Comment by arhuaco** [comment]
I ended up opting for an easier alternative. This one should work, I tested it and released it.
https://github.com/matrix-io/matrix-creator-init/commit/d8e9d350998177141a8d382dcf89a16a7a31d992
