### ISSUE TITLE
Improve the MCU programming verification process.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-creator-init#10]
Improve the MCU programming verification process.

**Comment by arhuaco** [comment]
@eljuguetero told me there are different ways to check this. Other than checking the output of the programming utility. This involves having a 'magic' signature in the firmware that can be queried to check if the programming succeeded.

**Comment by brianofrokk3r** [comment]
Perfect thank you @arhuaco

**Comment by brianofrokk3r** [comment]
@arhuaco I'm not sure if this is related, however we are experiencing issues with the MCU being programmed properly on reboot or start of Raspberry Pi. There are several issues that seem to be related, and unresolved so we need to prioritize this.
https://github.com/matrix-io/matrix-creator-malos/issues/8
http://community.matrix.one/t/zero-sensor-values/178

**Comment by arhuaco** [comment]
@brianofrokk3r I think we need help from  @eljuguetero or Kevin for this and then we can use their work to improve initialization. I could can try to work on MCU code with their help as well. I'll ask them.

**Comment by kdpatino** [comment]
@brianofrokk3r @arhuaco We improved how test firmware into SAM3S and EM358.
