### ISSUE TITLE
SAM3 firmware (blob/ch.bin) is 5 months old

### ISSUE THREAD

**Issue by vjoao** [matrix-io/matrix-creator-init#20]
Should this repository follow the `matrix-creator-mcu` release cycle and update itself?

**Comment by kdpatino** [comment]
Yes, the code in: https://github.com/matrix-io/matrix-creator-mcu, is the actual implementation of SAM3S firmware. MATRIX Creator init is the Debian package for the set-up configuration  and initial service for MATRIX Creator.
