### ISSUE TITLE
Manage failures during initialization

### ISSUE THREAD

**Issue by arhuaco** [matrix-io/matrix-creator-init#4]
In order to avoid MCU write cycles we are only programming it once.
For that,  we keep this file that serves as an "already programmed" flag.

```
/usr/share/admobilize/matrix-creator/sam3-program.bash.done
```

If this file exists the MCU is not programmed again.

This is failing once in a while and it's causing the demos to fail, getting zero values from drivers. For instance, for humidity we get:

```
{ humidity: 0, temperature: 0 }
```

The workaround is:

```
sudo rm /usr/share/admobilize/matrix-creator/sam3-program.bash.done
sudo /usr/share/admobilize/matrix-creator/sam3-program.bash
```

But we have to improve this.

**Comment by brianofrokk3r** [comment]
@arhuaco should a restart delete this `/usr/share/admobilize/matrix-creator/sam3-program.bash.done`?

**Comment by arhuaco** [comment]
@brianofrokk3r This would go against this requirement:

https://github.com/matrix-io/matrix-creator-init/issues/1

We need to improve the initialization anyway... It doesn't matter if we do it once or many times.

**Comment by arhuaco** [comment]
Duplicate of https://github.com/matrix-io/matrix-creator-init/issues/10 . Closing.
